services:
  - type: web
    name: repertoire
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /account/login/
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
